os: linux
dist: xenial

language: ruby
cache: bundler
rvm:
  - 2.5.3

before_install:
  - sudo apt-get install -y build-essential devscripts debhelper dh-make fakeroot
  - cd fits-1.4.0
  - sudo debuild -us -uc --lintian-opts --profile debian
install:
  - sudo apt install -y ../fits_1.4.0-1_all.deb

before_script:
  - gem install bundler
  - bundle install
script:
  - bundle exec rspec

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
