language: ruby
cache: bundler
rvm:
  - 2.5.3

before_install:
  - sudo apt-get install -y build-essential devscripts debhelper dh-make fakeroot
  - ./scripts/fits_util.thor build
install:
  - ./scripts/fits_util.thor install latest

before_script:
  - gem install bundler
  # no need to install byebug and other unused dev deps on travis
  - bundle install --without development
script:
  - bundle exec rspec

matrix:
  include:
    - os: linux
      dist: xenial
      env: OS="Ubuntu xenial (16.04)"
    - os: linux
      dist: trusty
      env: OS="Ubuntu trusty (14.04)"
    # precise doesn't recognize tar.xz
    # possibly change ont git now that orig.tar is tracked?
